<?php

declare(strict_types=1);

namespace Simensen\MessageTracing;

/**
 * Generates Trace Identities.
 *
 * Identities are generated by Traces, Trace Generators, and Trace Stacks.
 *
 * The storage type and method of identity generation is not prescribed
 * other than the strong suggestion to ensure every call to generate
 * an identity results in a globally unique identity.
 *
 * @see Trace
 * @see TraceGenerator
 * @see TraceStack
 *
 * @template TIdentity
 */
interface TraceIdentityGenerator
{
    /**
     * @return TIdentity
     */
    public function generateTraceIdentity(): mixed;
}
