<?php

declare(strict_types=1);

namespace Simensen\MessageTracing\TraceIdentity;

use Simensen\MessageTracing\Trace\Trace;
use Simensen\MessageTracing\Trace\TraceGenerator;
use Simensen\MessageTracing\TraceStack\TraceStack;

/**
 * Generates Trace Identities.
 *
 * Identities are generated by Traces, Trace Generators, and Trace Stacks.
 *
 * The storage type and method of identity generation is not prescribed
 * other than the strong suggestion to ensure every call to generate
 * an identity results in a globally unique identity.
 *
 * @see Trace
 * @see TraceGenerator
 * @see TraceStack
 *
 * @template TIdentity
 */
interface TraceIdentityGenerator
{
    /**
     * @return TIdentity
     */
    public function generateTraceIdentity(): mixed;
}
